version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - automerge
    versioning-strategy: 'lockfile-only'
  - package-ecosystem: 'github-actions'
    registries:
      - github-octocat
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - automerge
